### ISSUE TITLE
Height and width not getting set for the webcam widget

### ISSUE THREAD

**Issue by sumitshinde-84** [sumitshinde-84/node-red-dashboard-2-ui-webcam#1]
Height and width are not being set for the webcam widget, getting reset to the default 'auto'.

@joepavitt, could you please take a look?

**Comment by joepavitt** [comment]
This is happening because you've not declared `width` and `height` as values on the node. They need to be nested inside `defaults {}`, whereas you have them on the parent object at the moment.

**Comment by joepavitt** [comment]
Another good practice to follow is to use CSS classes, instead of inline CSS in `style=""` options. This makes your styling overridable by others if they want to declare there own in a `ui-template` node for example.

**Comment by joepavitt** [comment]
Just spotted a mistake that's my fault, the `category` option in the `.ui-webcam.html` still points to `flowforge`, rather than `flowfuse`, so it appears i the wrong section in the Node-RED Editor.

I'll update the `ui-example` too.

**Comment by joepavitt** [comment]
Underlying `ui-example` nodes improved based on the above: https://github.com/FlowFuse/node-red-dashboard-2-ui-example/pull/6

**Comment by sumitshinde-84** [comment]
Hii @joepavitt 
Thanks for all your valuable suggestions :) . Your insights are incredibly helpful, and I'm committed to implementing each one. I appreciate your support!

**Comment by sumitshinde-84** [comment]
Hi @joepavitt, all suggestions have been implemented. Whenever you have a moment, take a look and let me know what changes are required. I will quickly apply them.
